/*
	McKinney_A02Q3.java

	Write a program that computes and displays the result of rolling 
	several 6-sided dice and adding a number. Prompt the user for the 
	number of dice and the number to add. Display values read from the 
	user as shown below. [15 points].
*/

import java.util.*;	// For Scanner and Random classes

public class McKinney_A02Q3 {

	public static void main(String[] args) {

		int numberOfDice;		// Number of six sided dice to 'roll' as entered by user 
		int randomRoll;			// To hold random integer generated by 'dice roll'
		int addNumber;			// Entered by user, add number to result of 'randomRoll'
		int totalResult = 0;	// Final number after adding 'randomRoll' and 'addNumber'

		Scanner keyboard = new Scanner(System.in);

		System.out.print("How many dice would you like to roll? ");
		numberOfDice = keyboard.nextInt();

		System.out.print("What number should be added to the result? ");
		addNumber = keyboard.nextInt();

		Random rand = new Random();

		int count = 0;
		while (count != numberOfDice)
		{
			count++;
			randomRoll = rand.nextInt(6) + 1;
			System.out.println("Roll " + count + " was " + randomRoll);
			totalResult += randomRoll;
		}

		totalResult += addNumber;
		System.out.println("The result of rolling " + numberOfDice + " dice and " + 
							"adding " + addNumber + " is " + totalResult);
		
	}
}